# Azure Subscription ID
# This is a unique identifier for your Azure subscription
subscriptionId: "your-subscription-id-here"

# Azure Tenant ID
# This is the unique identifier for your Azure Active Directory (Azure AD) tenant
tenantId: "your-tenant-id-here"

# Azure Client ID (Application ID)
# This is the unique identifier for your Azure AD application (service principal)
clientId: "your-client-id-here"

# Azure Client Secret
# This is the secret key associated with your Azure AD application (service principal)
clientSecret: "your-client-secret-here"
